### ISSUE TITLE
Remove usage of `score` and `model_dataset_type_count`

### ISSUE THREAD

**Issue by mauroz77** [PDCMFinder/cancer-models#204]
## Description
Currently, the endpoint `api/search_index` includes the columns `score` and `model_dataset_type_count`, which contain numeric values that can be used to sort results in a search. Besides, `score` value is used as the `Model characterisation` value for a model.

With the implementation of [Support configuration of multiple model characterizations](https://app.zenhub.com/workspaces/pdcmfinder-board-5f0f036188f27e0014a7bdfc/issues/gh/pdcmfinder/pdcm-lectern-validator/11), the `api/search_index` endpoint includes a new column, `scores`, which contains a JSON object with all the metadata scores implemented in the ETL. This new column makes both `score` and `model_dataset_type_count`, so they will be eventually removed from the table and therefore the endpoint.

## `scores` column
So far, we have 2 model characterizations implemented: `PDX Metadata Characterization` and `Data Characterization`. 

The score that `PDX Metadata Characterization` produces is the replacement of what currently is in the score column, while `Data Characterization`'s score is the replacement for model_dataset_type_count.

An example of the `scores` content is the following:
```
{
    "data_score": 42,
    "pdx_metadata_score": 86
}
```

## Changes in sorting
Values in a JSON column can still be used to sort in PostgREST. The syntax changes to include both the column name and the attribute in the JSON object to use as a value to order by.

```
order=[json_column]->[attribute].[asc or desc]
```
In this specific example, if we want to sort asc by pdx_metadata_score:
```
https://dev.cancermodels.org/api/search_index?select= external_model_id,scores&limit=1000&order=scores->>pdx_metadata_score.asc
```

**Comment by mriios** [comment]
@mauroz77 You mention these values are replacements from the previous ones. Is it a structure replacement or formula/value too? I do see different values in old vs new structure, but I'm not sure if that's the intention.

Is this ready to be implemented in the FE?

**Comment by mauroz77** [comment]
@mriios This ticket was blocked by another one but I just closed it, so assigning this to you, as it's now ready to be implemented.
The changes described in the ticket are already applied to the dev environment. The production environment still doesn't have them, so we need to run the ETL in prod before you can merge these UI changes in prod. I still don't know when to run the ETL in production but it shouldn't be a blocker for implementing this and deploying in dev.

Yes, values are different and it's intended. Regarding your other question, not sure I get it. We can have a call if needed. In short, search_index.score is now search_index.scores->>pdx_metadata_score and search_index. model_dataset_type_count is now search_index.scores->>data_score.

**Comment by mriios** [comment]
Will implement in dev, then!

You did answer my question (:
